#!/usr/bin/env node
/**
 * sync-abis.mjs — regenerate frontend contract ABIs from forge artifacts.
 *
 * Reads forge artifacts under `contracts/out/` and writes:
 *   web/src/abi/Vault.ts         → export const vaultAbi = [...] as const
 *   web/src/abi/FaucetToken.ts   → export const faucetTokenAbi = [...] as const
 *   web/src/abi/ERC20.ts         → export const erc20Abi = [...] as const
 *
 * ERC20 is the standard ERC-20 subset of the FaucetToken artifact
 * (9 standard functions + Transfer/Approval events).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(repoRoot, 'contracts', 'out')
const abiDir = join(repoRoot, 'web', 'src', 'abi')

/** Read the `abi` array from a forge artifact. */
function readAbi(artifactPath, label) {
  let raw
  try {
    raw = readFileSync(join(outDir, artifactPath), 'utf8')
  } catch {
    throw new Error(
      `sync-abis: missing artifact for ${label} at ${artifactPath} — run \`forge build\` first`,
    )
  }
  const artifact = JSON.parse(raw)
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`sync-abis: artifact for ${label} has no abi array`)
  }
  return artifact.abi
}

/** Standard ERC-20 subset (functions + events) of a full token ABI. */
const ERC20_STANDARD_ITEMS = new Set([
  'name',
  'symbol',
  'decimals',
  'totalSupply',
  'balanceOf',
  'allowance',
  'approve',
  'transfer',
  'transferFrom',
  'Transfer',
  'Approval',
])

function toTsModule(exportName, abi) {
  return `// Auto-generated by scripts/sync-abis.mjs — DO NOT EDIT.\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const\n`
}

const vaultAbi = readAbi(join('Vault.sol', 'Vault.json'), 'Vault')
const faucetTokenAbi = readAbi(join('FaucetToken.sol', 'FaucetToken.json'), 'FaucetToken')

const erc20Abi = faucetTokenAbi.filter(
  (item) =>
    (item.type === 'function' || item.type === 'event') && ERC20_STANDARD_ITEMS.has(item.name),
)
if (erc20Abi.length !== 11) {
  throw new Error(`sync-abis: expected 11 standard ERC-20 items, got ${erc20Abi.length}`)
}

mkdirSync(abiDir, { recursive: true })
writeFileSync(join(abiDir, 'Vault.ts'), toTsModule('vaultAbi', vaultAbi))
writeFileSync(join(abiDir, 'FaucetToken.ts'), toTsModule('faucetTokenAbi', faucetTokenAbi))
writeFileSync(join(abiDir, 'ERC20.ts'), toTsModule('erc20Abi', erc20Abi))

console.log('sync-abis: wrote Vault.ts, FaucetToken.ts, ERC20.ts')
